#!/bin/bash

LIGHT_BLUE='\033[1;34m'
RED='\033[0;31m'
NC='\033[0m' # No Color
INTERACTIVE=""
FORCE_DELETE=""
MASTER="master"
while [[ $# -gt 0 ]]
do
  key="$1"
  case $key in
    -f)
    FORCE_DELETE="y"
    shift
    ;;
    -i)
    INTERACTIVE="i"
    shift
    ;;
    -fi|-if)
    INTERACTIVE="i"
    FORCE_DELETE="y"
    shift
    ;;
    -h)
    echo "$(basename $0) -i Intecative deletion of local branches"
    echo "$(basename $0) -f Force delete the branch(es)"
    echo "$(basename $0)    List local branches with creation and last update date"
    exit
    ;;
    *)
    shift
  esac
done

for brnch in $(git branch | sed /\*/d); do
  created_commit_id=$(git merge-base ${brnch} ${MASTER})
  created_date=$(git log --pretty=format:"%ad" --date=short -n 1 ${created_commit_id})
  created_ago=$(git log --pretty=format:"%cr" --date=short -n 1 ${created_commit_id})
  last_updated_date=$(git log --pretty=format:"%ad" --date=short -n 1 ${brnch})
  updated_before=$(git log --pretty=format:"%cr" --date=short -n 1 ${brnch})
  printf "Branch: ${brnch} was created on ${created_date}${RED}(${created_ago})${NC} and was last updated on ${last_updated_date}${RED}(${updated_before}${NC})\n"
  if [ "${INTERACTIVE}" == "i" ]; then
    printf "${LIGHT_BLUE}Delete the branch, followed by [y/n]?${NC} "
    read ip
    if [ "$ip" == "y" ]; then
      if [ "${FORCE_DELETE}" == "y" ]; then
        git branch -D ${brnch}
      else
        git branch -d ${brnch}
        if [ $? -ne 0 ]; then
          printf "${LIGHT_BLUE}Run with -fi command to delete ${brnch}${NC}\n"
        fi
      fi
    fi
  fi
done
